version: '3.1'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/theme
    working_dir: /theme
    networks:
      - nginx-load-balancer
    restart: always
    command: tail -f /dev/null
networks:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
