version: '3.1'
services:
  node:
    image: node:lts-alpine
    volumes:
      - ./:/theme
      - ./../../../../nginx-load-balancer/docker/mkcert/accountabilityhack.nl/:/certs/
    working_dir: /theme
    ports:
      - '3000:3000'
      - '3001:3001'
    networks:
      - nginx-load-balancer
    restart: always
    command: tail -f /dev/null
networks:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
